### DISCUSSION TITLE
개발로그

### DISCUSSION THREAD

**Discussion by minglet** [Pseudo-Lab/JobPT#7] [General]
## 안내 사항
매주 1개씩 자신의 작업물에 대해서 짧게 요약하는 문서 입니다. 
아래의 예시를 참고하여 모임(매주 화요일 8시 30분) 전까지 업로드 해주세요!

### Last Week

유저 이력서와 가장 유사한 JD 추천

- 샘플데이터 수집
    - JD & 이력서 수집
- 샘플 이력서 간단한 전처리
- word2vec 문서 유사도 검사 실험
- RAG pipeline 제작
- JD chunk에 대한 retrieval Test

### Next Week

- RAG pipeline 검증
    - 더 많은 샘플 데이터 실험
- VectorDB 셋업
- Prompt Engineering
- 유저 이력서 parsing 테스트

**Comment by MinwooKim1990** [comment]
## Last Week
SmolAgent 사용 가능성
https://github.com/MinwooKim1990/SmolAgent
레포에 1. Internet Search Agent, 2. AgenticRAG, 3. Vison Browsing Agent

### SmolAgent
- 장점: 
(1) 다양한 모델 사용이 쉬움
(2) Tool 구성이 특별히 어렵지 않음 (json schema 대신 function description으로 사용 가능)
(3) 에이전트 구성이 간편 (오케스트레이터 구현이 간단하며 서브 에이전트들도 간편)
(4) 로그가 잘 구성됨
- 단점:
(1) 로그가 너무 많아서 눈 아픔
(2) 멀티에이전트 단점으로 토큰 사용량이 많음

## Next Week
Internet Search Agent -> 회사 검색 결과 비교해보기
AgentRAG -> Phase 1 에 사용된 DB로 테스트
JobPT phase 1의 omniparser를 새로운 파서로 바꾸고 테스트

**Comment by byungchul-chae** [comment]
## 25.03.18
### Last Week
- Local LLM vs API
  - RTX4080(16GB VRAM) 환경에서 실험
  - DeepSeek-R1-Qwen-Distill:7b, 14b, 32b / EXAONE-Deep-7.8B &rarr; 32b 제외 나머지 원할한 실행 가능
- Finetuning?
  - unsloth 이용하면 finetuning 가능 &rarr; single gpu(무료)일 경우 2배 성능 향상 기대
  - finetuning이 우선순위인가?
    - prompt tuning, rag가 먼저인가? &rarr; finetuning 자체의 의미는 있음, but 기간, 리소스 고려해야함
    - 평가는 어떻게 할것인가? &rarr; API와 로컬LLM 평가 기준 필요함 / RAGAS..?  
### Next Week
- 현재 API 모델 / 로컬 모델 서치한 지표를 통해 우선적으로 점수 매겨보기
- 로컬 모델로 언제든지 바꿀 수 있게 준비해야함
- 수정제안 Agent 팀(with 재강님)
  - Reference 찾기 / 프로토타입 만들기

**Comment by hykhhijk** [comment]
# Last Week  
- RAG 리뷰 및 리서칭
  - query는 metadata 정보들이, passage는 JD의 description이 들어감
  - 여러 기법을 비교하기 위해서는 Retrieval을 평가하기 위한 지표가 필요함
- 평가지표
  - 정답포함vs두 문장비교에서 정답 passage를 포함하는것을 tp로 두고 정확도를 비교하는 쪽이 좋아보임 
  - 이번 task에서 passage를 맞춘다 = CV-JD가 매칭한다

# Next Week
둘 다 진행해보고 더 좋은 방법으로 결정할 예정
1. CV-JD가 매칭되는 데이터셋을 찾는다
2. 수집된 JD를 기반으로 LLM을 통해 합격or불합격 CV를 생성한다  

어떤 방식으로든 현재 Retrieval을 거치면 점수가 나오게끔 하는걸 목표로 삼고 추후 Retrieval에 여러 vectorDB, chunking등 바꿔끼워가며 실험진행 예정

**Comment by minglet** [comment]
## Last Week
summary agent 실험
- input: JD, company name
- 사용 모델: gpt-4o mini
- 아래의 키워드 중심의 회사 정보 수집 요청
  - Industry & Domain
  - Competitors
  - Company Background
  - Talent Profile
  - Future & Outlook
  - Ongoing Projects & Initiatives

### Thought
- 생각보다 더 긴 내용 → 마지막 Summary만 수정 제안 agent에 들어가도 괜찮을지 실험 필요할 듯
- 더 많은 케이스의 실험 필요 → 유명하지 않은 회사 & 잘 모르는 도메인의 회사
- 가장 유의미한 키워드를 뽑아주는 것도 좋을 듯 → 이력서에 키워드 중심으로 수정하면 될 것 같아서..
- 추가로 메타 데이터로 넣을 만한 것도 계속해서 디벨롭해야할 듯

## Next Week
- 추가 실험
    - 긴 JD vs 짧은 JD
    - 유명하지 않은 회사 & 잘 모르는 도메인의 회사
- 더 유의미한 요소에 대한 고민
    - 회사의 대표적인 프로덕트
    - 추진하는 사업
    - 다른 경쟁사보다 우위에 있는 것
- search tool 정확성 검증

**Comment by workdd** [comment]
# 25.03.18

# Last Week
JobPT Season1 버전 Docker compose로 띄우는 작업 진행

시행착오
1. OmniParser V1 Batch size 설정
   - OmniParser에서 default batch size가 None으로 처리 되어있어서 에러가 나는 경우가 발생했음.
   - OmniParser의 utils.py에서 기본 batch size값을 None이 아닌 1로 처리하여 에러 나는 경우가 없도록 수정
   - 수정된 OmniParserV1.zip 파일을 구글 드라이브에 재 업로드
2. Docker compose volume 문제
   - OmniParser에서 내부적으로 이미지를 저장할 때, /tmp 경로로 지정해 줌
   - web 도커 이미지와 api 도커 이미지가 서로 각각의 환경의 /tmp 경로를 가지고 있어 공유가 불가능함
   - Docker compose로 서버를 띄울 시, 공유 volume을 /tmp로 지정해두어 로컬 컴퓨터의 /tmp를 도커 환경 /tmp와 동일시함
3. Docker compose host 문제
   - web 이미지에서 api 이미지의 /matching api를 호출해야 하는데, 서로 각각의 다른 환경이여서 통신이 불가능한 문제 발생
   - network_model: "host" 옵션을 통해, 두 이미지가 모두 서버를 띄우는 컴퓨터 host의 환경과 동일시하는 옵션을 추가하여 해결

최종 Docker compose yaml 파일
```
version: "3"
services:
        api:
            image: ${DOCKER_USERNAME}/jobpt:api
            network_mode: "host"
            environment:
                - OPENAI_API_KEY=${OPENAI_API_KEY}
            volumes:
                - ./data:/app/data
                - /tmp:/tmp

        web:
            image: ${DOCKER_USERNAME}/jobpt:web
            network_mode: "host"
            environment:
                - OPENAI_API_KEY=${OPENAI_API_KEY}
            volumes:
                - ./data:/app/data
                - /tmp:/tmp
 ```

LangGraph 이해 및 실습 코드를 진행

# Next Week
- 수정 제안 Agent 및 검토 LLM 방법론 고안
- LangGraph 코드 작업 진행
